import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms — SellSniper",
  description: "Terms of service for SellSniper.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-black text-white font-sans">
      <div className="max-w-2xl mx-auto px-6 py-20">
        <Link href="/" className="text-sm text-zinc-500 hover:text-white">
          ← back
        </Link>
        <h1 className="text-4xl font-bold mt-6 mb-2">Terms</h1>
        <p className="text-xs text-zinc-500 mb-10">Last updated: 19 April 2026</p>

        <div className="space-y-8 text-zinc-300 leading-relaxed text-sm">
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">Using SellSniper</h2>
            <p className="text-zinc-400">
              SellSniper is a tool for creators who want to find the right audience for
              their work. By using it, you agree to use it in good faith — to distribute
              things you made or are authorised to promote.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">Don&apos;t abuse it</h2>
            <ul className="list-disc pl-5 space-y-1 text-zinc-400">
              <li>Do not attempt to circumvent the rate limit (scripted scraping, IP rotation, etc.).</li>
              <li>Do not scan competitors to harass, stalk, or reverse-engineer their users.</li>
              <li>
                Do not copy-paste the drafted messages as literal spam. They are starting
                points meant to be personalised and posted where the community&apos;s rules
                permit. Each platform&apos;s own guidelines always take precedence.
              </li>
              <li>Do not submit URLs that contain malware, illegal content, or CSAM.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">AI output disclaimer</h2>
            <p className="text-zinc-400">
              Results are generated by a large language model and may be inaccurate,
              outdated, or invent communities that don&apos;t exist. Treat every suggestion
              as a starting hypothesis — verify the subreddit, handle, or forum exists
              and that posting there is welcome before you act. SellSniper offers
              suggestions, not guarantees.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">Liability</h2>
            <p className="text-zinc-400">
              SellSniper is provided &quot;as is&quot; without warranties of any kind. To the
              maximum extent permitted by law, Anchor Marianas LLC is not liable for any
              indirect, incidental, or consequential damages arising from your use of the
              service, including bans or strikes you receive on third-party platforms
              from posting drafted messages.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-2">Changes & contact</h2>
            <p className="text-zinc-400">
              We may update these terms as the product evolves — the &quot;last updated&quot;
              date above will change. Questions go to{" "}
              <a href="mailto:adam@anchormarianas.com" className="text-red-400 hover:text-red-300">
                adam@anchormarianas.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
